name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Installing dotenv-vault
        run: |
          npm install dotenv@latest --save-dev
      - name: Decrypt and Generate env from key
        shell: bash
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY_STAGING }}
        run: |
          npx dotenv-vault@latest decrypt "$DOTENV_KEY" >> .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: mrdiamond12312/e-neighbor-render-api:latest

      - name: Async - Manually Trigger OnRender deploy
        if: github.ref == 'refs/heads/master'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"
